// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Common.Interfaces;
using System;
using System.Collections.Generic;

namespace AMDAuto.Entities
{
    public partial class CarOperations : IEntity
    {
        public Guid CarId { get; set; }
        public Guid OperationId { get; set; }
        public Guid? UserId { get; set; }
        public DateTime? CreatedOne { get; set; }

        public virtual Cars Car { get; set; }
        public virtual Operations Operation { get; set; }
        public virtual Users User { get; set; }
    }
}