// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Common.Interfaces;
using System;
using System.Collections.Generic;

namespace AMDAuto.Entities
{
    public partial class CarParts : IEntity
    {
        public CarParts()
        {
            CarPartsUsage = new HashSet<CarPartsUsage>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public int? Quantity { get; set; }
        public Guid? OperationId { get; set; }
        public double? Price { get; set; }

        public virtual Operations Operation { get; set; }
        public virtual ICollection<CarPartsUsage> CarPartsUsage { get; set; }
    }
}