// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Common.Interfaces;
using System;
using System.Collections.Generic;

namespace AMDAuto.Entities
{
    public partial class Cars : IEntity
    {
        public Cars()
        {
            Appointments = new HashSet<Appointments>();
            CarOperations = new HashSet<CarOperations>();
            PastAppointments = new HashSet<PastAppointments>();
        }

        public Guid Id { get; set; }
        public string LicenseNumber { get; set; }
        public int? ReleaseYear { get; set; }
        public Guid? UserId { get; set; }
        public int MakeNameId { get; set; }
        public int ModelId { get; set; }

        public virtual MakeNames MakeName { get; set; }
        public virtual ModelNames Model { get; set; }
        public virtual Users User { get; set; }
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual ICollection<CarOperations> CarOperations { get; set; }
        public virtual ICollection<PastAppointments> PastAppointments { get; set; }
    }
}