// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Common.Interfaces;
using System;
using System.Collections.Generic;

namespace AMDAuto.Entities
{
    public partial class Employees : IEntity
    {
        public Employees()
        {
            Appointments = new HashSet<Appointments>();
        }

        public Guid Id { get; set; }
        public Guid UserId { get; set; }

        public virtual Users User { get; set; }
        public virtual ICollection<Appointments> Appointments { get; set; }
    }
}