// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Common.Interfaces;
using System;
using System.Collections.Generic;

namespace AMDAuto.Entities
{
    public partial class Photos : IEntity
    {
        public Guid Id { get; set; }
        public byte[] Content { get; set; }
    }
}