// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Common.Interfaces;
using System;
using System.Collections.Generic;

namespace AMDAuto.Entities
{
    public partial class Reviews : IEntity
    {
        public Reviews()
        {
            Comments = new HashSet<Comments>();
        }

        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        public string Content { get; set; }
        public DateTimeOffset? CreatedOn { get; set; }

        public virtual Users User { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}