// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Common.Interfaces;
using System;
using System.Collections.Generic;

namespace AMDAuto.Entities
{
    public partial class Users : IEntity
    {
        public Users()
        {
            Appointments = new HashSet<Appointments>();
            CarOperations = new HashSet<CarOperations>();
            Cars = new HashSet<Cars>();
            Comments = new HashSet<Comments>();
            Employees = new HashSet<Employees>();
            PastAppointments = new HashSet<PastAppointments>();
            Reviews = new HashSet<Reviews>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public DateTime? CreatedOn { get; set; }
        public Guid RoleId { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual Roles Role { get; set; }
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual ICollection<CarOperations> CarOperations { get; set; }
        public virtual ICollection<Cars> Cars { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<PastAppointments> PastAppointments { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}